### ISSUE TITLE
HW4 建議

### ISSUE THREAD

**Issue by johnwu1114** [fatelai/SkylineHomework#2]
範例程式 restful 的 api 命名方式不符合常規。

**Comment by fatelai** [comment]
Hi John:
請問您說的命名規則是指哪個部份呢
我在網路上有看到部分人說資源名稱後面通常用複數(homeworks)
還是您是指參數id的部分沒有使用path的方式傳入?
這部分我再來調整
[image: image.png]

John Wu ***@***.***> 於 2023年4月26日 週三 下午2:47寫道：

**Comment by johnwu1114** [comment]
以訂單為例，常見的命名方式：

1. 新增 POST /order
2. 修改 PUT /order/{id}
3. 刪除 DELETE /order
4. 查單一 GET /order/{id}
5. 查清單 GET /orders or /order/list
    (統一用單數或複數有不同派別，主要看團隊習慣)

**Comment by johnwu1114** [comment]
另外，可以看看 HATEOAS(Hypermedia As The Engine Of Application State) 原則

**Comment by fatelai** [comment]
已調整成以下規則

   1. 新增 POST /homework
   2. 修改 PUT /homework/{id}
   3. 刪除 DELETE /homework
   4. 查單一 GET /homework/{id}
   5. 查清單 GET /homework

homework為不可數，故不加s

 HATEOAS的文章會再找時間多看幾次

John Wu ***@***.***> 於 2023年4月26日 週三 下午5:52寫道：
